Player shooting system
FlamingoFiestaStudio/OlympusGoneWild pull request #116
Opened 2023-10-27 19:14 UTC by 201flaviosilva

### Description

- Created the bullet scene (currently using the Godot logo, (Blocked by #5 ));
- Implemented the player shooting system using gun system and timer;

### Image/Video

https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/55815265/4a074c2d-4274-4f19-a025-d8710d614571

### Related Issue

**Closes #7**

### Does this PR introduce a breaking change? ⚠️

- [X] No
- [ ] Yes

### Tests

- [X] I tested all game E2E;
- [ ] I just tested some scenes;
- [ ] Not applicable.

### Check list

Before submitting this pull request, please ensure the following are completed:

- [X] [My commits follow the project conventions](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/wiki/ProjectBestPractices#commit-message-convections).
- [ ] My code follows the project's coding style and conventions.
- [ ] I have updated the project documentation (if necessary).
- [ ] My code makes sense with the design.

## Additional Notes

If you do not agree with some value, let me know.

---

Thank you for your contribution to Olympus Gone Wild! Your effort is greatly appreciated, and it helps make this project better for everyone. 😄🎮🚀

2023-10-28 11:23 UTC, Gabriel-Sous-a requested changes

2023-10-28 11:23 UTC, Gabriel-Sous-a commented on player/Gun.gd
I think `Weapon.gd` would be a better name for this file

2023-10-28 11:23 UTC, Gabriel-Sous-a commented on player/Gun.gd
> +@onready var gun: Marker2D = get_node(".")
Same thing here

2023-10-28 11:23 UTC, Gabriel-Sous-a commented on player/Player.gd
> +func _on_gun_shoot(Bullet: PackedScene, _position: Vector2, _direction: Vector2) -> void:
same thing here

2023-10-29 11:41 UTC, Gabriel-Sous-a approved these changes

2023-11-02 12:26 UTC, Goncalo-FP reviewed
I think player should be shooting slower.

2023-11-06 16:39 UTC, LeoHabs approved these changes
Seems fine to me

2023-11-06 22:47 UTC, merged