feat(#70): Add a camera.
FlamingoFiestaStudio/OlympusGoneWild pull request #84
Opened 2023-10-09 17:28 UTC by Goncalo-FP

### Description

Added a camera that follows the player. 

### Image/Video

https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/128065979/975d7cd0-e961-4c85-a291-82787ba937a3

### Related Issue

None 

### Does this PR introduce a breaking change? ⚠️

- [ ] No
- [ ] Yes 

### Tests

- [ ] I tested all game E2E;
- [ ] I just tested some scenes;
- [ ] Not applicable.

### Check list

Before submitting this pull request, please ensure the following are completed:

- [ ] [My commits follow the project conventions](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/wiki/ProjectBestPractices#commit-message-convections).
- [ ] My code follows the project's coding style and conventions.
- [ ] I have updated the project documentation (if necessary).
- [ ] My code makes sense with the design.

## Additional Notes

---

Thank you for your contribution to Olympus Gone Wild! Your effort is greatly appreciated, and it helps make this project better for everyone. 😄🎮🚀

2023-10-09 21:18 UTC, Gabriel-Sous-a requested changes

2023-10-09 21:18 UTC, Gabriel-Sous-a commented on Player/Player.tscn
> +[ext_resource type="Texture2D" uid="uid://csenw0x4vfg0d" path="res://Player/sprites/run/player-run-6.png" id="11_0g20g"]
the folder to use is `player` not `Player`

2023-10-09 21:18 UTC, Gabriel-Sous-a commented on main/level_1.tscn
> +[ext_resource type="PackedScene" uid="uid://ey7qekfsbkai" path="res://Player/Player.tscn" id="1_lqipx"]
same thing here

2023-10-09 22:07 UTC, 201flaviosilva commented on Player/Player.tscn
> +zoom = Vector2(0.7, 0.7)
For now don't make sense (we don't have map), but probably it's something we will want?

`limit_smoothed = true`

2023-10-13 21:05 UTC, Gabriel-Sous-a approved these changes

2023-10-13 21:41 UTC, 201flaviosilva approved these changes

2023-10-13 21:59 UTC, merged