Implement Map
FlamingoFiestaStudio/OlympusGoneWild pull request #88
Opened 2023-10-10 22:53 UTC by Adan0k

### Description

Added map to level_1 scene

### Image/Video

![image](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/42160712/5ea9e76b-5650-4282-b92f-062385a3e277)

### Related Issue

**Closes #69**

### Does this PR introduce a breaking change? ⚠️

- [x] No
- [ ] Yes 

### Tests

- [ ] I tested all game E2E;
- [x] I just tested some scenes;
- [ ] Not applicable.

### Check list

Before submitting this pull request, please ensure the following are completed:

- [ ] [My commits follow the project conventions](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/wiki/ProjectBestPractices#commit-message-convections).
- [ ] My code follows the project's coding style and conventions.
- [ ] I have updated the project documentation (if necessary).
- [ ] My code makes sense with the design.

## Additional Notes
The border already have colision, to the player don't go out of map

---

Thank you for your contribution to Olympus Gone Wild! Your effort is greatly appreciated, and it helps make this project better for everyone. 😄🎮🚀

2023-10-11 10:14 UTC, Gabriel-Sous-a commented
the branch name should be like this [wiki](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/wiki/ProjectBestPractices#branch-naming-convention)

2023-10-11 22:49 UTC, Gabriel-Sous-a requested changes
After testing saw that the map is implemented however there are no borders. And maybe you should expand a bit the map

2023-10-13 21:35 UTC, 201flaviosilva commented
> After testing saw that the map is implemented however there are no borders. And maybe you should expand a bit the map

![Captura de ecrã 2023-10-13 223308](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/55815265/c360e436-073c-4ada-9c1a-d5ce36278d92)

yap not working

2023-10-13 21:39 UTC, 201flaviosilva requested changes

2023-10-13 21:39 UTC, 201flaviosilva commented on main/assets/y5w2xwP.png
Please reference where you got this image and confirm if we can use it, if it is free to be used in the project, we don't want to have legal problems

And give a better name to this file, like TileFlor :)

2023-10-13 21:39 UTC, 201flaviosilva commented on main/level_1.tscn
> +[node name="TileMap" type="TileMap" parent="."]
Create a scene for this, probably we will use it in more places, and clears this file :)

2023-10-16 10:27 UTC, Gabriel-Sous-a commented
When started the player is not centered on the map:

<img width="578" alt="Screenshot 2023-10-16 at 11 25 44" src="https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/116306408/e4a0fdb0-8b0a-4605-87d2-78df85532593">

And the borders still dont work:

<img width="580" alt="Screenshot 2023-10-16 at 11 25 19" src="https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/116306408/57b3e2fe-fc22-4f94-bc9b-73a97564a4a5">

2023-10-16 10:31 UTC, Gabriel-Sous-a commented
In the PR description the tests are applicable, and the commits aren't following the project conventions so please have that checked

2023-10-16 10:32 UTC, Gabriel-Sous-a commented on main/assets/y5w2xwP.png
TileFloor* 😁

2023-10-16 11:14 UTC, Adan0k commented
> When started the player is not centered on the map:
> 
> <img width="578" alt="Screenshot 2023-10-16 at 11 25 44" src="https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/116306408/e4a0fdb0-8b0a-4605-87d2-78df85532593">
> 
> And the borders still dont work:
> 
> <img width="580" alt="Screenshot 2023-10-16 at 11 25 19" src="https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/116306408/57b3e2fe-fc22-4f94-bc9b-73a97564a4a5">
> 

When I was testing, i placed the player next to the border to not lose time walking.

2023-10-16 23:00 UTC, Gabriel-Sous-a commented
Like I said before the branch name is not following the project conventions, neither is the PR. But the borders are working!

2023-10-17 01:15 UTC, closed without merging